allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.14 || 57.0.24'
  - '@expo/fingerprint@0.20.7 || 0.20.13'
  - '@expo/inline-modules@0.1.5'
  - '@expo/local-build-cache-provider@57.0.6'
  - '@expo/metro-config@57.0.8'
  - '@expo/prebuild-config@57.0.11 || 57.0.16'
  - expo-asset@57.0.10 || 57.0.17
  - expo-constants@57.0.10 || 57.0.18
  - expo-server@57.0.2
  - expo@57.0.12 || 57.0.22
  - '@expo/metro-runtime@57.0.9'
  - '@expo/ui@57.0.10 || 57.0.18'
  - expo-dev-client@57.0.11 || 57.0.19
  - expo-dev-launcher@57.0.11 || 57.0.20
  - expo-dev-menu@57.0.11
  - expo-router@57.0.12 || 57.0.21
  - jest-expo@57.0.4
  - expo-file-system@57.0.7
  - expo-font@57.0.4
  - expo-glass-effect@57.0.3
  - expo-image@57.0.5
  - expo-json-utils@57.0.2
  - expo-keep-awake@57.0.2
  - expo-linking@57.0.10
  - expo-localization@57.0.2
  - expo-manifests@57.0.2
  - expo-modules-autolinking@57.0.13
  - expo-modules-core@57.0.18
  - expo-sqlite@57.0.3
  - expo-symbols@57.0.3
  - expo-updates-interface@57.0.2
nodeLinker: hoisted
