name: Android production build

on:
  push:
    tags:
      - "v*"

jobs:
  build_android:
    name: Build Android production AAB
    type: build
    environment: production
    params:
      platform: android
      profile: production

  submit_android:
    name: Submit Android to Google Play internal testing
    needs: [build_android]
    type: submit
    environment: production
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: production
