import type { RecipeCatalog } from "../domain";

import catalogJson from "./generated/catalog.json";

/**
 * Immutable catalog shipped with the application. It is generated by
 * `scripts/generate-catalog.mjs` and checked by `scripts/validate-catalog.mjs`.
 */
export const bundledRecipeCatalog = catalogJson as RecipeCatalog;
